version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
      - dotnet restore DotnetCoreLambdaExample/DotnetCoreLambdaExample.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output DotnetCoreLambdaExample/DotnetCoreLambdaExample.csproj
artifacts:
  type: zip
  files:
    - DotnetCoreLambdaExample/build_output/**/*
